services:
  api:
    image: flask_api:ci
    container_name: "flask_api"
    environment:
      POETRY_VIRTUALENVS_CREATE: "false"
      POETRY_VIRTUALENVS_IN_PROJECT: "false"
    build: .
    ports:
      - ${PORT:-5000}:5000
    command: python ./src/server.py
    volumes:
      - ./:/app:rw
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 5s
      timeout: 3s
      retries: 60
      start_period: 5s
